version: "3"
services:
  db:
    image: mysql:latest
    container_name: mysql-db2
    ports:
      - "3306:3306"
    networks:
      - oneworld-network
    restart: always
    environment:
      MYSQL_DATABASE: userdb
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: pa@@word
    volumes:
        - db-data:/var/lib/mysql

  onewa-user-service:
    container_name: onewa-user-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    networks:
      - oneworld-network
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db2:3306/userdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: ahmed
      SPRING_DATASOURCE_PASSWORD: mysql

volumes:
    db-data:

networks:
  oneworld-network:
    driver: bridge