server:
  port: 9000

spring:
  profiles:
    active: dev

  flyway:
    enabled: true
    baseline-on-migrate: true

app:
  mail:
    base-url: http://localhost:9000
    from: jekii.kabiru@gmail.com
