server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: mysql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: validate
    generate-ddl: true
    show-sql: true


  thymeleaf:
    cache: false
    mode: HTML

  mail:
    defaultEncoding: UTF-8
    host: email-smtp.eu-west-1.amazonaws.com
    password: ' '
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp
    username: ''

flyway:
  enabled: true
  baseline-on-migrate: true

app:
  mail:
    base-url: http://localhost:9000
    from: noreply@oneworld.com
